### ISSUE TITLE
Code style template

### ISSUE THREAD

**Issue by kwadie** [sscdotopen/trackthetrackers#14]
Hi @sscdotopen  
Can you export the eclipse\IntelliJ code formatter that you are using for this project and share it somewhere here please? 

Thanks,
Karim

**Comment by sscdotopen** [comment]
I don't have a special formatter. We use Sun's Java code conventions  [1] with 2 spaces indentation and a maximum line length of 120.

 [1] http://www.oracle.com/technetwork/java/codeconvtoc-136057.html

**Comment by FelixNeutatz** [comment]
intellij -> settings -> editor -> Code Style

Tab size: 2
Indent: 2
Continuation: 4

intellij -> settings -> editor -> Code Style -> Java

Tab size: 2
Indent: 2
Continuation: 4

intellij -> settings -> editor -> Code Style -> Scala

Tab size: 2
Indent: 2
Continuation: 4
